"""empty message

Revision ID: 1a9f196d43b2
Revises: None
Create Date: 2015-08-17 18:06:31.273894

"""

# revision identifiers, used by Alembic.
revision = '1a9f196d43b2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
