"""empty message

Revision ID: 2728b7328b78
Revises: d7c7f3be40a
Create Date: 2015-10-20 13:44:12.129389

"""

# revision identifiers, used by Alembic.
revision = '2728b7328b78'
down_revision = 'd7c7f3be40a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conference_schedule')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conference_schedule',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('entry', sa.VARCHAR(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
