"""empty message

Revision ID: 2798bc43117a
Revises: c7c5c7d112c
Create Date: 2016-02-12 23:02:59.822880

"""

# revision identifiers, used by Alembic.
revision = '2798bc43117a'
down_revision = 'c7c5c7d112c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.add_column(u'conference', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'conference', 'user', ['user_id'], ['id'])
    op.add_column(u'conference_profile', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'conference_profile', 'user', ['user_id'], ['id'])
    op.add_column(u'conference_schedule', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'conference_schedule', 'user', ['user_id'], ['id'])
    op.add_column(u'contact', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contact', 'user', ['user_id'], ['id'])
    op.add_column(u'participant', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'participant', 'user', ['user_id'], ['id'])
    op.add_column(u'participant_profile', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'participant_profile', 'user', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'participant_profile', type_='foreignkey')
    op.drop_column(u'participant_profile', 'user_id')
    op.drop_constraint(None, 'participant', type_='foreignkey')
    op.drop_column(u'participant', 'user_id')
    op.drop_constraint(None, 'contact', type_='foreignkey')
    op.drop_column(u'contact', 'user_id')
    op.drop_constraint(None, 'conference_schedule', type_='foreignkey')
    op.drop_column(u'conference_schedule', 'user_id')
    op.drop_constraint(None, 'conference_profile', type_='foreignkey')
    op.drop_column(u'conference_profile', 'user_id')
    op.drop_constraint(None, 'conference', type_='foreignkey')
    op.drop_column(u'conference', 'user_id')
    op.drop_table('roles_users')
    op.drop_table('user')
    op.drop_table('role')
    ### end Alembic commands ###
