"""empty message

Revision ID: c7c5c7d112c
Revises: 3a15e901e08c
Create Date: 2015-10-20 15:33:37.545510

"""

# revision identifiers, used by Alembic.
revision = 'c7c5c7d112c'
down_revision = '3a15e901e08c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conference_schedule', sa.Column('conference', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'conference_schedule', 'conference', ['conference'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conference_schedule', type_='foreignkey')
    op.drop_column('conference_schedule', 'conference')
    ### end Alembic commands ###
