"""empty message

Revision ID: d7c7f3be40a
Revises: 563f582d07fa
Create Date: 2015-10-20 13:40:57.501602

"""

# revision identifiers, used by Alembic.
revision = 'd7c7f3be40a'
down_revision = '563f582d07fa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conference_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conference_schedule')
    ### end Alembic commands ###
